### ISSUE TITLE
Implement stop times packing, with pattern sharing

### ISSUE THREAD

**Issue by laurentg** [mecatran/gtfsvtor#31]
The new TripTimesValidator using dao trip and times streaming will now allow a much more aggressive approach in stop time storing (either using packing and pattern sharing; or external storage).

For packing, use the following strategy:
- Only store time delta vs the first defined time.
- Use bit packing (3 bits for pickup/dropoff, remaining bits for variable length encoding and time unit)
- Use variable-length encoding (1 byte is often enough)
- Use special value for 0 in bit field (most of the time departure=arrival)
- Use variable unit of time (if rounded to the minute, use a bit)
- Share the common packed time delta sequences (will be often the same for trips)
- Share common stop ID / seq / dist traveled patterns

**Comment by laurentg** [comment]
@hbruch You may want to test that code with some large feed of yours? This code should help memory-wise.

By the way, what are your test settings for your large `20200522_fahrplaene_gesamtdeutschland` feed? I tested it locally, but -Xmx6G does not seems to be enough.

**Comment by laurentg** [comment]
@hbruch As a side note, I plan to do the same (delta-packing of IE7 shape points coordinates) for shape points. I will open an issue.

**Comment by hbruch** [comment]
@laurentg I rerun with the current `20200605_fahrplaene_gesamtdeutschland` feed and commit 04705113f8854ab77e7a0c2c3a7c2bd948187b24, no additionally supplied config, running under corretto 11 with -Xmx6G under MacOs. A complete run with that GTFSVTOR version now took 2:29 min. Even with -Xmx4G, GTFSVTOR completed in 2:35 min.
I'm looking forward to your shape point packing improvements.

**Comment by laurentg** [comment]
@hbruch Many thanks for this. Did you noticed some improvement memory-wise? What worries me is that those numbers are noticeably worse than you original tests you mention on the gtfs-changes mailing-list (even though the original number were suspiciously good).

**Comment by hbruch** [comment]
Yes, the first numbers were too good, as the java 11 issue (#1) prevented auto detection of the tests. Memory usage improved, since before your changes, I had to explicitly increase memory, now 4G are sufficient.
