### ISSUE TITLE
Re-use stop pattern internal data for shape linear indexer

### ISSUE THREAD

**Issue by laurentg** [mecatran/gtfsvtor#55]
Linear shape indexer compute for each trip a stop pattern key to aggregate data per stop pattern. Since this data is already available in the stop dao implementation for each trip, we should refactor the code to make use of it. This would fasten the code and decrease memory use.

**Comment by laurentg** [comment]
@hbruch This should improve the performances on DELFI, I manage to run on 4G on my machine w/o issues now (which was not the case before).

**Comment by hbruch** [comment]
I'll test and report. Thanks already, @laurentg !
