### ISSUE TITLE
GTFSVTOR seems not to detect incorrect speed limit at terminus

### ISSUE THREAD

**Issue by ghost** [mecatran/gtfsvtor#80]
Example in this feed :

https://www.data.gouv.fr/fr/datasets/r/024123a0-8665-4983-90bd-134ef7d70383

In trip 13-15335686146, order 5 to 6, speed is over 100 but doesn't detected even fith parameters file set to 75.

**Comment by laurentg** [comment]
Hi @Benjamin-BERTELLE 
The slack for time w/o seconds is 60 sec, so the speed computation is:
`speed = d / (t + slack)`

Here in this dataset d ~= 700m, t = 1mn, slack = 1mn, so compared speed is around 5.8 m/s (around 20km/h).

Unfortunately the slack time is not configurable (it is 0 for time with seconds specified such as 10:03:27, and 60 seconds for time w/o seconds such as 10:03). Anyway here, even w/o slack time the speed would be 40km/h (700m in 1 min).

Anyway, how did you computed the speed of 100 km/h?
